import { createHash, randomBytes } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { env } from "../../config/env";
import { forbidden, notFound } from "../../core/errors";

/**
 * File storage.
 *
 * Local disk behind a narrow interface, so swapping in S3 or GCS later touches
 * only this file. Stored names are random — never the name the uploader chose —
 * because a filename is attacker-controlled input and reusing it invites path
 * traversal, overwrite collisions and content-type confusion. The original name
 * is kept in the database as a label.
 *
 * Files are laid out per company, which makes a tenant's stored bytes trivially
 * enumerable for deletion or export and keeps directories small.
 */
export interface StoredFile {
  storageKey: string;
  sizeBytes: number;
  checksum: string;
}

export async function storeFile(companyId: string, buffer: Buffer, extension: string): Promise<StoredFile> {
  const safeExtension = normaliseExtension(extension);
  const key = path.posix.join(companyId, `${randomBytes(16).toString("hex")}${safeExtension}`);
  const absolute = resolveKey(key);

  await fs.mkdir(path.dirname(absolute), { recursive: true });
  await fs.writeFile(absolute, buffer, { mode: 0o600 });

  return {
    storageKey: key,
    sizeBytes: buffer.byteLength,
    checksum: createHash("sha256").update(buffer).digest("hex"),
  };
}

export async function readFile(storageKey: string): Promise<Buffer> {
  try {
    return await fs.readFile(resolveKey(storageKey));
  } catch {
    throw notFound("File", storageKey);
  }
}

export async function deleteFile(storageKey: string): Promise<void> {
  try {
    await fs.unlink(resolveKey(storageKey));
  } catch {
    // A missing file is the desired end state; deleting the row still matters.
  }
}

/**
 * Resolve a storage key to an absolute path, refusing anything that escapes the
 * upload root. Keys are generated by this module, but treating them as
 * untrusted costs nothing and closes the path-traversal class outright.
 */
function resolveKey(storageKey: string): string {
  const absolute = path.resolve(env.uploadDir, storageKey);
  const root = path.resolve(env.uploadDir);
  if (absolute !== root && !absolute.startsWith(root + path.sep)) {
    throw forbidden("Invalid storage key.");
  }
  return absolute;
}

function normaliseExtension(extension: string): string {
  const cleaned = extension.toLowerCase().replace(/[^a-z0-9.]/g, "");
  if (!cleaned.startsWith(".") || cleaned.length > 12) return "";
  return cleaned;
}
